### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by iamsee** [agileago/webpack-mutiple#2]
很感谢您的代码，但是我在npm run dev 的时候回报错，新手请教
$ npm run dev

> webpack-mutiple@0.0.1 dev /Volumes/OS-DATA/WorkSpace/PhpSpace/truesign/apps_front
> node build/server.js

module.js:474
    throw err;
    ^

Error: Cannot find module '../manifest.json'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/OS-DATA/WorkSpace/PhpSpace/truesign/apps_front/build/webpack.base.js:50:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! webpack-mutiple@0.0.1 dev: `node build/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-mutiple@0.0.1 dev script 'node build/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-mutiple package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-mutiple
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-mutiple
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/OS-DATA/WorkSpace/PhpSpace/truesign/apps_front/npm-debug.log

**Comment by FuGangqiang** [comment]
@agileago , 
不知这个 issue 为何被关闭？
按照 readme 中的说明，现在还是会出现类似问题：
```
> node build/server.js

module.js:472
    throw err;
    ^

Error: Cannot find module '../manifest.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fu/Test/test/my-project/build/webpack.base.js:49:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Linux 4.9.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! webpack-mutiple@0.0.1 dev: `node build/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-mutiple@0.0.1 dev script 'node build/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-mutiple package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-mutiple
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-mutiple
npm ERR! There is likely additional logging output above.
```

npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@4.1.2
3 info using node@v7.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle webpack-mutiple@0.0.1~predev: webpack-mutiple@0.0.1
6 silly lifecycle webpack-mutiple@0.0.1~predev: no script for predev, continuing
7 info lifecycle webpack-mutiple@0.0.1~dev: webpack-mutiple@0.0.1
8 verbose lifecycle webpack-mutiple@0.0.1~dev: unsafe-perm in lifecycle true
9 verbose lifecycle webpack-mutiple@0.0.1~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/fu/Test/test/my-project/node_modules/.bin:/home/fu/.pyenv/plugins/pyenv-virtualenv/shims:/home/fu/.pyenv/shims:/home/fu/.pyenv/bin:/home/fu/.local/bin:/home/fu/.cargo/bin:/home/fu/.gem/ruby/2.3.0/bin:./node_modules/.bin:/home/fu/.node_modules/bin:/home/fu/.pyenv/plugins/pyenv-virtualenv/shims:/home/fu/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/lib/emscripten:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle webpack-mutiple@0.0.1~dev: CWD: /home/fu/Test/test/my-project
11 silly lifecycle webpack-mutiple@0.0.1~dev: Args: [ '-c', 'node build/server.js' ]
12 silly lifecycle webpack-mutiple@0.0.1~dev: Returned: code: 1  signal: null
13 info lifecycle webpack-mutiple@0.0.1~dev: Failed to exec dev script
14 verbose stack Error: webpack-mutiple@0.0.1 dev: `node build/server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid webpack-mutiple@0.0.1
16 verbose cwd /home/fu/Test/test/my-project
17 error Linux 4.9.6-1-ARCH
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
19 error node v7.4.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error webpack-mutiple@0.0.1 dev: `node build/server.js`
22 error Exit status 1
23 error Failed at the webpack-mutiple@0.0.1 dev script 'node build/server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webpack-mutiple package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs webpack-mutiple
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls webpack-mutiple
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by agileago** [comment]
@FuGangqiang   https://github.com/agileago/webpack-mutiple/tree/master/template#首先打包公共资源vendor-公共资源配置在-packagejson中统一管理

**Comment by FuGangqiang** [comment]
谢谢，没看清楚 :)
